### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by nofxx** [propublica/upton#40]
Can we get a new version? =D
rest-client is now in version ~> 1.8.x
Thank you!

**Comment by jeremybmerrill** [comment]
@nofxx No problem, glad Upton's useful to you! 0.3.4 -- same as 0.3.3, but with newer Nokogiri and RestClient -- is now up at https://rubygems.org/gems/upton

**Comment by nofxx** [comment]
@jeremybmerrill thank you!
